name = "Rowan's Server"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01b76e1e6fa4d98cb245fcc0f06a9e5a75143a08d40b8a58586287e49fbd811d"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
