name = "Rowan's Server"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cae177122ff3d97798d1805715a3497debe0f64d9096cadd5358b2eb6ded9ef"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
