name = "Rowan's Server"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcc4b6700ae683bc02399e28327b12db4ca4b2251ba9f69d54e1f504a112d663"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
