name = "Rowan's Server"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2125cee7222dfc20d838b6a3d89519725fc6084401e236ebd525e2d97f12cc5"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
